### ISSUE TITLE
neurosynth changed to a new file format

### ISSUE THREAD

**Issue by K-Z-W** [gzanitti/B2RIO#1]
https://github.com/gzanitti/B2RIO/blob/92927e7046c745696b45457775b53afbbc3edfcf/b2rio/b2rio.py#L80

In August 2021, the Neurosynth database was reorganized according to a new file format

**Comment by margulies** [comment]
Just a suggestion, but changing the path to [https://github.com/neurosynth/neurosynth-data/raw/e8f27c4a9a44dbfbc0750366166ad2ba34ac72d6/current_data.tar.gz](https://github.com/neurosynth/neurosynth-data/raw/e8f27c4a9a44dbfbc0750366166ad2ba34ac72d6/current_data.tar.gz) seems to do the trick

**Comment by demianw** [comment]
Hot fix by @margulies , the proper fix should be updating the system to use the current format. This is included in the new version of NeuroLang @gzanitti see https://github.com/NeuroLang/NeuroLang/blob/7fef01fc253d774c7bf4d875342a437146b0f00a/neurolang/frontend/neurosynth_utils.py

**Comment by gzanitti** [comment]
As recommended by @demianw, the new version of B2RIO uses the latest version of NeuroLang to get the Neurosynth files. Thank you for your feedback.
